##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## makes files
##

SRC	=	my_compute_square_root.c        \
		my_sort_int_array.c	\
		my_strcapitalize.c	\
		my_find_prime_sup.c	\
		my_str_isalpha.c	\
		my_str_islower.c	\
		my_str_isprintable.c	\
		my_str_isupper.c	\
		my_compute_power_rec.c	\
		my_getnbr.c	\
		my_isneg.c	\
		my_is_prime.c	\
		my_putchar.c	\
		my_put_nbr.c	\
		my_putstr.c	\
		my_printf.c	\
		my_printf2.c	\
		my_printf3.c	\
		my_revstr.c	\
		my_showmem.c	\
		my_showstr.c	\
		my_strcat.c	\
		my_strcmp.c	\
		my_strcpy.c	\
		my_str_isnum.c	\
		my_strlen.c	\
		my_strlowcase.c	\
		my_strncat.c	\
		my_strncmp.c	\
		my_strncpy.c	\
		my_strstr.c	\
		my_strupcase.c	\
		my_swap.c	\
		my_strdup.c	\
		my_putnbr_money.c	\

OBJ	=	$(SRC:.c=.o)

NAME	=	libmy.a

all:	$(NAME)

$(NAME):	$(OBJ)
	ar rc $(NAME) $(OBJ)

clean:
	rm -f *.o $(OBJ)

fclean: clean
	rm -f $(NAME)
re: all clean
